### PR TITLE
Added MacOS layout and how to do on MacOS

### PR DESCRIPTION
**Pull request by skykosiner**
A few months ago when I used MacOS I created this exact layout but with MacOS so I just added on how to do it and the code to do it

### CODE REVIEW

**Comment by cesar-programs** [comment]
Thank you very much

**Comment by vybhavab** [comment]
Are you able to use shortcuts like CMD + Shift + { ? to move between tabs in a web browser? It works on qwerty but sadly not when using this layout

**Comment by vegerot** [comment]
How is this different than `Real\ Programmers\ Dvorak.bundle/Contents/Resources/Real\ Programmers\ Dvorak.keylayout`?

**Comment by ThePrimeagen** [comment]
i haven't used a mac in 69 years so i figured it wsa correct / not my problem (same thing)

**Pull request merged**
